name: poc_pattern
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  analysis_server_plugin: any
  analyzer: any
  analyzer_plugin: any
  # path: ^1.9.0

dev_dependencies:
  analyzer_testing: any
  test_reflective_loader: any
  lints: ^6.0.0
  test: ^1.25.6
